project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  navbar:
    background: transparent
    left: 
      - text: Jeppe Fjeldgaard Qvist
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Workshops
        href: workshop.qmd
      - text: Publications
        href: publications.qmd
      - text: cv
        href: cv.qmd

format:
  html:
    css: styles.css
    theme:
      - lux # morph, superhero, united, lux 
    highlight-style: zenburn
    include-before-body:
      - https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:ital,wght@0,100;0,400;0,700;0,900;1,100;1,400;1,700;1,900&display=swap
    toc: true

execute:
  freeze: auto