project:
  type: website

website:
  title: ""
  search: false
  navbar:
    background: transparent
    left:
      - text: "<img src='images/monster.png' alt='Logo' style='height: 50px; vertical-align: middle;'>"
        href: index.qmd 
    right:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Workshops
        href: workshop.qmd
      - text: Publications
        href: publications.qmd
      - text: cv
        href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
